import type { AvailableThemes, Theme } from "../main";

const themes: Record<AvailableThemes, Theme> = {
    "default": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        folderFileNameColor: "#cccccc",
        focusedTabFileBgColor: "#2f2f2f",
        standbyTabFileBgColor: "#181818",
        focusedTabFileNameColor: "#ffffff",
        standbyTabFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        closeTabButtonBgColor: "#4d4d4d",
        selectedThing: "#0078d4",
        componentSeparatorBorderColor: "#414141",
        caretColor: "#828282",
        iconColor: "1",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955"
    },
    "light": {
        primaryBgColor: "#f3f3f3",
        secondaryBgColor: "#ffffff",
        folderFileNameColor: "#616161",
        folderSelectedFileBgColor: "#e4e6f1",
        focusedTabFileBgColor: "#ffffff",
        standbyTabFileBgColor: "#ececec",
        focusedTabFileNameColor: "#333333",
        standbyTabFileNameColor: "#333333b3",
        closeTabButtonBgColor: "#b8b8b84f",
        selectedThing: "#0078d4",
        componentSeparatorBorderColor: "#cfcfcf",
        caretColor: "#000000",
        iconColor: "0",
        tagName: "#800000",
        tagBracket: "#800000",
        attrName: "#e50000",
        attrAssign: "#000000",
        attrValue: "#0000ff",
        text: "#000000",
        comment: "#008000"
    },
    "dark": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        folderFileNameColor: "#cccccc",
        focusedTabFileBgColor: "#2f2f2f",
        standbyTabFileBgColor: "#181818",
        focusedTabFileNameColor: "#ffffff",
        standbyTabFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        closeTabButtonBgColor: "#4d4d4d",
        selectedThing: "#0078d4",
        componentSeparatorBorderColor: "#414141",
        caretColor: "#828282",
        iconColor: "1",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955"
    },
    "monokai": {
        primaryBgColor: "#1d1e19",
        secondaryBgColor: "#272822",
        folderFileNameColor: "#919288",
        folderSelectedFileBgColor: "#c0c1b50d",
        focusedTabFileBgColor: "#1d1e19",
        standbyTabFileBgColor: "#1d1e19",
        focusedTabFileNameColor: "#e6db74",
        standbyTabFileNameColor: "#919288",
        closeTabButtonBgColor: "#5a5d5e4f",
        selectedThing: "#e6db74",
        componentSeparatorBorderColor: "#161613",
        caretColor: "#ffffff",
        iconColor: "1",
        tagName: "#f92672",
        tagBracket: "#919288",
        attrName: "#66d9ef",
        attrAssign: "#919288",
        attrValue: "#e6db74",
        text: "#fdfff1",
        comment: "#6e7066"
    },
    "dracula": {
        primaryBgColor: "#282a36",
        secondaryBgColor: "#21222c",
        folderFileNameColor: "#f8f8f2",
        folderSelectedFileBgColor: "#44475a75",
        focusedTabFileBgColor: "#282a36",
        standbyTabFileBgColor: "#21222c",
        focusedTabFileNameColor: "#f8f8f2",
        standbyTabFileNameColor: "#6272a4",
        closeTabButtonBgColor: "#373a42",
        selectedThing: "#94527e",
        componentSeparatorBorderColor: "#606168",
        caretColor: "#f8f8f2",
        iconColor: "1",
        tagName: "#ff79c6",
        tagBracket: "#f8f8f2",
        attrName: "#50fa7b",
        attrAssign: "#ff79c6",
        attrValue: "#f1fa8c",
        text: "#f8f8f2",
        comment: "#6272a4"
    }
};

export default themes;