import type { Theme } from "../main";

const themes: Record<"default" | "light" | "dark" | "monokai" | "dracula", Theme> = {
    "default": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        selectedFileColor: "#0078d4",
        folderFileNameColor: "#cccccc",
        selectedFileNameColor: "#ffffff",
        standbyFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955",
    },
    "light": {
        primaryBgColor: "",
        secondaryBgColor: "",
        selectedFileColor: "",
        folderFileNameColor: "",
        selectedFileNameColor: "",
        standbyFileNameColor: "",
        folderSelectedFileBgColor: "",
        tagBracket: "",
        tagName: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: "",
    },
    "dark": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        selectedFileColor: "#0078d4",
        folderFileNameColor: "#cccccc",
        selectedFileNameColor: "#ffffff",
        standbyFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955",
    },
    "monokai": {
        primaryBgColor: "",
        secondaryBgColor: "",
        selectedFileColor: "",
        folderFileNameColor: "",
        selectedFileNameColor: "",
        standbyFileNameColor: "",
        folderSelectedFileBgColor: "",
        tagBracket: "",
        tagName: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: "",
    },
    "dracula": {
        primaryBgColor: "",
        secondaryBgColor: "",
        selectedFileColor: "",
        folderFileNameColor: "",
        selectedFileNameColor: "",
        standbyFileNameColor: "",
        folderSelectedFileBgColor: "",
        tagBracket: "",
        tagName: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: "",
    }
};

export default themes;