import type { AvailableThemes, Theme } from "../main";

const themes: Record<AvailableThemes, Theme> = {
    "default": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        folderFileNameColor: "#cccccc",
        focusedTabFileBgColor: "#2f2f2f",
        standbyTabFileBgColor: "#181818",
        focusedTabFileNameColor: "#ffffff",
        standbyTabFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        closeTabButtonBgColor: "#4d4d4d",
        selectedThing: "#0078d4",
        componentSeparatorBorderColor: "#414141",
        caretColor: "#828282",
        iconColor: "1",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955"
    },
    "light": {
        primaryBgColor: "",
        secondaryBgColor: "",
        folderFileNameColor: "",
        folderSelectedFileBgColor: "",
        focusedTabFileBgColor: "",
        standbyTabFileBgColor: "",
        focusedTabFileNameColor: "",
        standbyTabFileNameColor: "",
        closeTabButtonBgColor: "",
        selectedThing: "",
        componentSeparatorBorderColor: "",
        caretColor: "",
        iconColor: "0",
        tagName: "",
        tagBracket: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: ""
    },
    "dark": {
        primaryBgColor: "#181818",
        secondaryBgColor: "#1f1f1f",
        folderFileNameColor: "#cccccc",
        focusedTabFileBgColor: "#2f2f2f",
        standbyTabFileBgColor: "#181818",
        focusedTabFileNameColor: "#ffffff",
        standbyTabFileNameColor: "#9d9d9d",
        folderSelectedFileBgColor: "#464646",
        closeTabButtonBgColor: "#4d4d4d",
        selectedThing: "#0078d4",
        componentSeparatorBorderColor: "#414141",
        caretColor: "#828282",
        iconColor: "1",
        tagBracket: "#808080",
        tagName: "#569cd6",
        attrName: "#9cdcfe",
        attrAssign: "#cccccc",
        attrValue: "#ce9178",
        text: "#cccccc",
        comment: "#6a9955"
    },
    "monokai": {
        primaryBgColor: "",
        secondaryBgColor: "",
        folderFileNameColor: "",
        folderSelectedFileBgColor: "",
        focusedTabFileBgColor: "",
        standbyTabFileBgColor: "",
        focusedTabFileNameColor: "",
        standbyTabFileNameColor: "",
        closeTabButtonBgColor: "",
        selectedThing: "",
        componentSeparatorBorderColor: "",
        caretColor: "",
        iconColor: "0",
        tagName: "",
        tagBracket: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: ""
    },
    "dracula": {
        primaryBgColor: "",
        secondaryBgColor: "",
        folderFileNameColor: "",
        folderSelectedFileBgColor: "",
        focusedTabFileBgColor: "",
        standbyTabFileBgColor: "",
        focusedTabFileNameColor: "",
        standbyTabFileNameColor: "",
        closeTabButtonBgColor: "",
        selectedThing: "",
        componentSeparatorBorderColor: "",
        caretColor: "",
        iconColor: "0",
        tagName: "",
        tagBracket: "",
        attrName: "",
        attrAssign: "",
        attrValue: "",
        text: "",
        comment: ""
    }
};

export default themes;